### PR TITLE
Voron Trident Dock

### PR DESCRIPTION
**Pull request by mneuhaus**
The 2.4 Dock and Variable Dock take up quite a lot of space which could be better used for nozzle scrubbing etc.
I've created an alternative Dock, that attaches to the rear left vertical profile.

trident_dock

### CODE REVIEW

**Comment by jlas1** [comment]
Hi, that's a nice dock, I can add it to usermods, i'm creating printer specific directories, so it may take a while

**Comment by mneuhaus** [comment]
Thanks!
Don't worry, anyone interested can easily grab it from here in the mean time :)

**Comment by Pixeltrace-GER** [comment]
Hi,
I haven't testet this dock, but it shows a collision between Carriage and XY Joint in the picure above. I don't know how accurate the picture is. ;-)

**Comment by Markus-1984** [comment]
Hi,
@mneuhaus nice dock mount for the Trident. It works well!

@Pixeltrace-GER I can confirm that there is NO colission.

**Comment by mneuhaus** [comment]
Yea, there is no collision, i modeled it based on the official Voron CAD files, so it should fit on any official trident.

**Comment by jlas1** [comment]
Hi, the dock is now 2mm smaller, con you move it 2mm to the front and if possible update the PR with the new file structure and placed here:
https://github.com/jlas1/Klicky-Probe/tree/main/Printers/Voron/v1.8_v2.4_Legacy_Trident/Usermods
I can also export the CAD and stl and do these changes if you allow me.

**Pull request merged**
