### PR TITLE
Dragon UHF Klicky Probe in UserMods

### PR DESCRIPTION
**Pull request by SemperDiscere**
This is an extended Probe for use with the Dragon UHF hotend (17mm longer than standard).

If this needs to be somewhere else, just let me know.  Cad files included.
Klicky Only, I don't have an NG or UnKlicky to test on.

### CODE REVIEW

**Comment by rembart** [comment]
works nice, thanks!

**Comment by Ramalama2** [comment]
> What is the point of increasing the size of the probe, if the same result can be done simply by extruding toolhead probe mount? By choosing this path instead, you do not need to pointlessly solder wires to the microswitch.

The point is:
Printing one of these and nothing needs to be exchanged...
You can have the probe somewhere lieing around.
So to switch to the dragon uhf, you simply switch the duct and exchange the probe.
You can do that often and it's fast done.

Otherwise you have to:
Remove the duct (you have to do that anyway, so this doesn't count actually), replace the probe mount, which is finnicky and takes a bit more time as just replacing the duct...
Because you have the cables there that goes to the magnet and probably a ziptie....

And after that you have to replace the dock with a longer one either....
And then you have to mount it on the exact same x position (accurate to mm) to not change the dock position in the macro again...

What's the point of that? 🤦🤷
Cheers

**Comment by SemperDiscere** [comment]
> What is the point of increasing the size of the probe, if the same result can be done simply by extruding toolhead probe mount? By choosing this path instead, you do not need to pointlessly solder wires to the microswitch.

Because I can swap between UHF Dragon and *any other toolhead* by swapping just the toolhead and probe, not having to rerun the wires and mess with the carriage mount.  I can also print one that is I shorter (I think 7mm) and swap the UHF's nozzle extension out if I wanted to.  

Requires no Dock changes.

**Comment by jlas1** [comment]
There is now a similar version of this, it just prints on the side instead of on it's back, but it's a valid approach and i will include it.

Thanks for the PR.

**Pull request merged**
