### PR TITLE
Modified Klicky Dock

### PR DESCRIPTION
**Pull request by Alexander-T-Moss**
Added the CAD and STL for a modified Klicky dock that has the magnet more recessed in the dock to reduce it's strength and allow for more reliable undocking. Links to [issue #84](https://github.com/jlas1/Klicky-Probe/issues/84)

### CODE REVIEW

**Comment by jlas1** [comment]
Let me check it, you removed the slot in the front that allows to remove the magnet easily.
I assume that you also tested with the latest dock, can you just confirm?

**Comment by Alexander-T-Moss** [comment]
I was using an older version of the dock, so I can test the latest one out and see how it goes. If that also has similar issues I'll update my modified one to include the magnet removal slot.

**Comment by Alexander-T-Moss** [comment]
Oops, didn't mean to close the pull request, will open a new one with updated files if I don't find success with the latest dock :)

**Comment by jlas1** [comment]
it should be ok, the new dock makes it impossible for the two magnets to
touch, so it reduces a lot the strength needed to separate them.

**Pull request closed without merging**
